language: R
cache: packages
sudo: false
warnings_are_errors: false

install:
  - ./travis-tool.sh install_github edgararuiz/rscontract

include:
  - r: release

after_success:
  - Rscript -e 'covr::codecov()'
